In [1]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

data = asarray([['bronze'], ['silver'], ['gold']])
print (data)

encoder = OrdinalEncoder()

result = encoder.fit_transform(data)
print(result)

[['bronze']
 ['silver']
 ['gold']]
[[0.]
 [2.]
 [1.]]


In [2]:
# !pip install category_encoders

In [3]:
import pandas as pd
from pandas import DataFrame
df = pd.DataFrame({'Award':['Bronze', 'Silver', 'Gold']})
print(df)

    Award
0  Bronze
1  Silver
2    Gold


In [4]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'],['green'], ['blue']])
print(data)

encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [5]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'],['green'], ['blue']])
print(data)

encoder = OneHotEncoder(drop='first',sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 1.]
 [1. 0.]
 [0. 0.]]


In [7]:
# Encoding categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

NameError: name 'X' is not defined